import { ProviderAdapter, normalizeResult, createTimeoutSignal, checkedJson, providerFailure, delegateTools } from './base.js'
import { providerConfig, resolveProviderKey } from './catalog.js'

const chatTools=delegateTools.map(tool=>({type:'function',function:{name:tool.name,description:tool.description,parameters:tool.parameters}}))
export function chatBody(query){const messages=[{role:'system',content:query.instruction||'Complete the bounded delegated task.'},{role:'user',content:JSON.stringify({task:query.task,context:query.context})}];if(query.continuation){messages.push({role:'assistant',content:JSON.stringify({request_context:query.continuation.request})},{role:'user',content:JSON.stringify({instruction:'Continue the same bounded task using only this approved evidence.',approvedEvidence:query.continuation.approvedEvidence})})}return{model:query.model,messages,reasoning_effort:query.effort,max_tokens:query.budget.maxOutputTokens,tools:chatTools,tool_choice:'auto'}}
export function parseChat(provider,query,value){const choice=value.choices?.[0]||{},message=choice.message||{},toolCalls=(message.tool_calls||[]).map(call=>({id:call.id,name:call.function?.name,arguments:call.function?.arguments}));return normalizeResult({provider,model:query.model,role:query.role,output:message.content||'',usage:{inputTokens:value.usage?.prompt_tokens,outputTokens:value.usage?.completion_tokens,totalTokens:value.usage?.total_tokens},finishReason:choice.finish_reason,metadata:{responseId:value.id,toolCalls,continuationRequired:toolCalls.some(call=>call.name==='request_context'),incomplete:choice.finish_reason==='length'}})}
export class ChatProvider extends ProviderAdapter {
  constructor(name,path,{env=process.env,fetchImpl=globalThis.fetch,timeoutMs}={}){super(name);this.path=path;this.env=env;this.fetch=fetchImpl;this.timeoutMs=timeoutMs}
  prepare(query){return chatBody(query)}
  async execute(query){const {key}=resolveProviderKey(this.name,this.env);if(!key)throw new Error(`${this.name.toUpperCase()}_API_KEY not configured`);const cfg=providerConfig(this.name),base=(this.env[cfg.baseUrlEnv]||cfg.defaultBaseUrl).replace(/\/$/,'');const timed=createTimeoutSignal(this.timeoutMs||query.timeoutMs||30000,query.signal);try{const response=await this.fetch(`${base}${this.path}`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify(this.prepare(query)),signal:timed.signal});return parseChat(this.name,query,await checkedJson(this.name,response))}catch(error){throw providerFailure(this.name,error,timed.signal)}finally{timed.cleanup()}}
}
